Error in file
Exception type: AttributeError
Exception message: 'DataFrame' object has no attribute 'Glasstype'
Stack trace:
File: Submissions/18001040.py
Line: 8
Func.Name: <module>
Message: y=data.Glasstype

File: /mnt/data/Linux/applications/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py
Line: 5274
Func.Name: __getattr__
Message: return object.__getattribute__(self, name)

